'''
The task in Question 4 should now be programmed object-oriented. 
a) Create a class diagram for the class(es) needed. The objects are instantiated using data from the input fields in the GUI layer.
 b) Write new code for "registering a comment on an image", requirements: 
 - Objects must be instantiated using data from the GUI input fields. 
 - Database update must be done via SQL statements with substitution using the object's instance variables.
- You do not need to reproduce the GUI code from Question 4.



'''