import tkinter as tk

window = tk.Tk()
f1 = tk.Frame(window)
f1.pack(side='left')
f2 = tk.Frame(window)
f2.pack(side='right')
reg_label = tk.Label(f1, text = 'Reg number')
reg_label.pack()
reg = tk.Entry(f1) 
reg.pack()
customer_label = tk.Label(f1, text = 'Customer name')
customer_label.pack()
customer_name = tk.Entry(f1)
customer_name.pack()
start_label = tk.Label(f1, text = 'Start date')
start_label.pack()
start_date = tk.Entry(f1)
start_date.pack()
end_label = tk.Label(f1, text = 'End date')
end_label.pack()
end_date = tk.Entry(f1)
end_date.pack()
status_label = tk.Label(f1, text = 'Status')
status_label.pack()
status = tk.Entry(f1)
status.pack()
total_label = tk.Label(f1, text = 'Total cost')
total_label.pack()
total_cost = tk.Entry(f1)
total_cost.pack()

button = tk.Button(f1, text = 'Enter data')
button.pack()

reg_label_2 = tk.Label(f2, text = 'Enter reg number to get data')
reg_label_2.pack()
reg_2 = tk.Entry(f2)
reg_2.pack()

button_2 = tk.Button(f2, text = 'Get data')
button_2.pack()

res = tk.Label(f2,text = '')
res.pack()

tk.mainloop()
